### ISSUE TITLE
Change icon

### ISSUE THREAD

**Issue by tristiisch** [echebbi/eclipse-discord-integration#66]
Is it possible to change the basic language icons?
Is it possible to choose one icon per project?
If not, can you add this feature? Or explain where to add this to your code? I would be happy to do that.

And to add a default icon, at the moment, they is no icon:
![image](https://user-images.githubusercontent.com/19597873/57988030-7c896c80-7a89-11e9-8cf8-de75d0c8660a.png)

**Comment by echebbi** [comment]
Hi,

## Not currently...

It is currently impossible to dynamically add new icons. In order to add a Rich Presence for Eclipse IDE I had to create a dedicated [Discord application](https://discordapp.com/developers/docs/rich-presence/how-to#initialization). Each application can have up to 150 assets, uploaded by the developer, and only these can be displayed as icons in Discord.

It has been asked to allow developers to dynamically add new assets but (AFAIK) the feature is not available yet. See:
 - https://github.com/discordapp/discord-rpc/issues/70
 - https://support-dev.discordapp.com/hc/en-us/community/posts/360043570772-Allowing-upload-of-assets-via-Hash

## ... but there may be a workaround

That being said, I believe that we could overcome this limit. Indeed, if assets are bound to a Discord application, then we "just" have to allow users to specify their own. Users could hence provide (and use) their own icons by:

1. Creating a new Discord application
2. Uploading their assets
3. Configure the Rich Presence plug-in so that it uses their application and their assets.

## So how to do that?

Here are the tasks that I can think of:

#### 1. Make the Discord application ID configurable

The ID of my application is currently hard-coded in the [DiscordRpcProxy](https://github.com/echebbi/eclipse-discord-integration/blob/636eb3f8f819b43792fb4b991823e39000cce3a1/bundles/fr.kazejiyu.discord.rpc.integration/src/fr/kazejiyu/discord/rpc/integration/core/DiscordRpcProxy.java#L27) class. This must change to allow users to specify their own:

 - either by default,
 - or by project.

The best way to do this should be to enhance the [UserPreferences](https://github.com/echebbi/eclipse-discord-integration/blob/636eb3f8f819b43792fb4b991823e39000cce3a1/bundles/fr.kazejiyu.discord.rpc.integration/src/fr/kazejiyu/discord/rpc/integration/settings/UserPreferences.java#L19) interface. It defines all the preferences that can be set by a user; you can take a look at its sub-classes to see how preferences are persisted and check [PreferredRichPresence](https://github.com/echebbi/eclipse-discord-integration/blob/636eb3f8f819b43792fb4b991823e39000cce3a1/bundles/fr.kazejiyu.discord.rpc.integration/src/fr/kazejiyu/discord/rpc/integration/core/PreferredRichPresence.java#L31) for an example of how these preferences are used to tailor the rich presence.

#### 2. Allow users to specify their own key

This can be achieved by adding new text fields:

- in the project's properties page (see [ProjectPropertiesPage.java](https://github.com/echebbi/eclipse-discord-integration/blob/636eb3f8f819b43792fb4b991823e39000cce3a1/bundles/fr.kazejiyu.discord.rpc.integration.ui.preferences/src/fr/kazejiyu/discord/rpc/integration/ui/preferences/properties/ProjectPropertiesPage.java#L54))
- in the plug-in's preferences page (see [DiscordIntegrationPreferencesPage](https://github.com/echebbi/eclipse-discord-integration/blob/636eb3f8f819b43792fb4b991823e39000cce3a1/bundles/fr.kazejiyu.discord.rpc.integration.ui.preferences/src/fr/kazejiyu/discord/rpc/integration/ui/preferences/DiscordIntegrationPreferencesPage.java#L32))

## Some resources

I do not know what is your technical background so here are a few resources that may be useful if you want to implement this:

- [Introduction to Discord Rich Presence](https://discordapp.com/developers/docs/rich-presence/how-to)
- [Introduction to the development of plug-ins for Eclipse IDE](https://www.vogella.com/tutorials/EclipsePlugin/article.html)
- [Introduction to Eclipse preferences API](https://www.vogella.com/tutorials/EclipsePreferences/article.html)
- [Contributing guide](https://github.com/echebbi/eclipse-discord-integration/blob/636eb3f/CONTRIBUTING.md)

If you have the time to implement a solution I would be glad to accept your contribution! I apologize for the long message but I preferred to be as comprehensive as possible. Feel free to ask any question if you face an issue or if the code is not clear enough.

## Regarding the default icon

I wanted to show Eclipse IDE's icon by default but I do not have the rights to use it. Available logos can be checked here:
 - https://www.eclipse.org/artwork/

I planned to contact the Eclipse Foundation to ask for their permission but I did not take the time to do it yet.

**Comment by echebbi** [comment]
I finally have some free time so I'm going to work on this.

**Comment by echebbi** [comment]
The feature is finally here :tada: As of `v1.1.0` you can ask the plug-in to rely on your own Discord application and thus provide your own icons.

That's not _that_ convenient but I believe that's the best we can do with current Discord's API.

I am currently writing a more detailed documentation but in the meantime here is what must be done to customize the icons shown on Discord:

1. Create a Discord Application:
    a. Connect to the [Discord Developer Portal](https://discordapp.com/developers/applications/) (you'll have to login with your Discord credentials)
    b. Click on `New Application`
    c. Specify the application name (it will be shown on Discord instead of _Eclipse IDE_)
2. Once in the application's settings page, upload your icons:
    a. Click on `Rich Presence` (see the navigation menu on the left)
    b. Click on `Add Image(s)`
    c. Select your icons, validate
    d. Scroll down, specify an ID for each icon then `Save Changes`
> Note: the ID allows me to use the right icon for the right language; you can find which ID I use for which language in [the Language](https://github.com/echebbi/eclipse-discord-integration/blob/2aba8c01d00776449c8ec2d1505bed328dca058a/bundles/fr.kazejiyu.discord.rpc.integration/src/fr/kazejiyu/discord/rpc/integration/languages/Language.java) class (it's the first parameter of enums)
3. Configure the plug-in to use your own Discord Application
    a. `Window` > `Preferences`
    b. `Discord Rich Presence` > `Icons`
    c. Check `Use custom application` then specify the ID of your application (it's the `Client ID` field on your application's main page)
    d. `Apply`
4. Discord should be updated with your own icons!

You can also set the setting per project.

I know that it looks like a lot of steps but it's actually pretty quick to do; enjoy!

<div align="center">
    <img alt="example of customized icon" src="https://user-images.githubusercontent.com/25926433/65750522-e46f5400-e108-11e9-8d07-90f797489135.png"/>
</div>

> Credit: icon by _Chanut is Industries_
>https://www.iconfinder.com/icons/2913096/castle_fantasy_fortress_kingdom_medieval_rpg_stronghold_icon

**Comment by Tristiisch74** [comment]
thanks !

**Comment by echebbi** [comment]
The documentation is now online:
- https://discord-rich-presence-for-eclipse-ide.readthedocs.io/en/latest/customize/change-language-icons.html

Feel free to submit a new bug if you find it unclear so that I can improve it.

**Comment by tristiisch** [comment]
I'm probably going to be a little demanding but if you could add the possibility of having this image in addition (with the eclipse logo of course) it would really be perfect!
![image](https://user-images.githubusercontent.com/19597873/66576114-6c2c7800-eb77-11e9-932d-530bb724830f.png)

**Comment by echebbi** [comment]
I just sent an e-mail to `license@eclipse.org` to ask for the authorization to display Eclipse IDE's logo. I have no idea whether the Eclipse Foundation will grant me the rights but at least we should have an answer soon.

I reopen the issue until then.

**Comment by echebbi** [comment]
I have been allowed by the Eclipse Foundation to display the logo of the Eclipse IDE! You should upgrade to `1.1.2` to benefit from it:

<div align="center">
<img alt="Example of Rich Presence showing Eclipse IDE's logo" src="https://user-images.githubusercontent.com/25926433/67623566-233b1b80-f827-11e9-9561-209aade70bf7.png"/>
</div>


I believe that this issue is definitely closed now. Please open a new one for any new bug or feature request.
