### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by Mavable** [echebbi/eclipse-discord-integration#77]
An option to only show that you work on a file but not the names etc.

**Comment by echebbi** [comment]
You mean showing for instance `Editing a file` instead of `Editing Foo.java`? I'd like to limit the number of available options so I won't provide it as-is.

#71 will allow users to customize the wording. You will then be able to ask the plug-in to follow a custom pattern, such as`"Writing in ${language}"` to show `"Writing in Java"` instead of `"Editing Foo.java"`. Would it suit your need?

Meanwhile you can still [hide the name of the edited file](https://discord-rich-presence-for-eclipse-ide.readthedocs.io/en/latest/customize/hide-information.html#).

**Comment by Mavable** [comment]
Yes absolutly!

Emmanuel Chebbi <notifications@github.com> schrieb am Sa. 18. Apr. 2020 um
16:01:

**Comment by echebbi** [comment]
The new [1.1.3 release](https://github.com/echebbi/eclipse-discord-integration/releases/tag/v1.1.3) provides [a way to customize wording](https://discord-rich-presence-for-eclipse-ide.readthedocs.io/en/latest/customize/change-wording.html). It should fulfill your needs:

<div align="center">
    <img src="https://user-images.githubusercontent.com/25926433/80817076-05cd7c80-8bd1-11ea-900f-139fbe08bef5.png" alt="example of customized Rich Presence"/>
</div>
